# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98b9f41b06c5e1a9a262f750f109e69fe68def96ed4b4d6ddb397b43fb7d7bb90b08b57214ed721dff07093a6d4d16cf4c5fd0239afe8ae791615dee7c3d1e9a

test:
  secret_key_base: 897b5b7c48982439c38f1ef38725fbd35f986c15b7b9fff31cd62e8c63945d2c34c67067c616b6ac49f1760adba83d49a36e2b679b0b8e10694c84aebae5c8b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
